name: capsule_endoscopy_labeler
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - streamlit
  - pandas
  - plotly
  - Pillow
  - google-api-python-client
  - google-auth
  - google-auth-httplib2
  - google-auth-oauthlib
  - openpyxl
